MODEL:
  NAME: 'MGN'
  POOL: 'MAX'
  LAST_STRIDE: 2 # MGN Stride Must to 2

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  HF_PROB: 0.5 # random horizontal flip
  PADDING: 10

  RE: True # enable random erasing
  RE_PROB: 0.5 # random erasing probability

DATASETS:
  NAMES: ('Market1501')
  STORE_DIR: './datasets'
  # STORE_DIR: '/Users/linshan/Pictures/Person_ReID_Datasets'
  # STORE_DIR: '../mfsNetwork/Datasets'

DATALOADER:
  NUM_WORKERS: 8

SOLVER:
<<<<<<< HEAD:config/mac_market_softmax.yaml
  OPTIMIZER_NAME: 'SGD'
=======
  LOSS: 'softmax_triplet'
  LAMBDA1: 2
  LAMBDA2: 1
  OPTIMIZER_NAME: 'Adam'
>>>>>>> 1fa25ffc32a03d50f5e66b18e3ffb60caba81733:config/Sample_Market1501_MGN_SoftmaxTriplet.yaml
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEP: 40
  GAMMA: 0.1

  WARMUP: True
  WARMUP_STEPS: [40, 70]
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 20
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 256

<<<<<<< HEAD:config/mac_market_softmax.yaml
OUTPUT_DIR: "./checkpoint/Market1501/Softmax_S1_BS64_SGD"
DEVICE: "cpu"
=======
OUTPUT_DIR: "./checkpoint/Market1501/Market_MGN_SoftmaxTriplet_S1_BS64"
DEVICE: "cpu"
# DEVICE: "cuda:1"
>>>>>>> 1fa25ffc32a03d50f5e66b18e3ffb60caba81733:config/Sample_Market1501_MGN_SoftmaxTriplet.yaml
